name: Tests 

on:
  pull_request:

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - uses: tj-actions/changed-files@v19
    
      - run: |
          for file in ${{ steps.changed-files.outputs.all_changed_files }}; do
              php tester.php $file
          done
